In [80]:
from pandas import read_csv, to_datetime

In [41]:
import matplotlib.pyplot as plt
from math import isnan

In [81]:
from datetime import datetime

In [ ]:
#Zapisanie pliku csv do dataframe

In [11]:
df = read_csv("data/samsung-health-stress-data.csv", header = 0, usecols=[1,6,7,8,9,10,16], names=["Start time", "Update time", "Create time","Max", "Min", "Score","End time"])

In [13]:
df.tail()

,Start time,Update time,Create time,Max,Min,Score,End time
14135,2026-03-17 19:00:00.000,2026-03-17 20:07:50.744,2026-03-17 19:32:21.941,93.0,0.0,7.0,2026-03-17 19:59:59.999
14136,2026-03-17 20:00:00.000,2026-03-17 21:04:07.081,2026-03-17 20:44:52.381,98.0,0.0,27.0,2026-03-17 20:59:59.999
14137,2026-03-17 21:00:00.000,2026-03-17 23:55:03.819,2026-03-17 21:04:08.081,98.0,0.0,16.0,2026-03-17 21:59:59.999
14138,2026-03-17 23:00:00.000,2026-03-18 00:00:04.694,2026-03-17 23:55:03.924,0.0,0.0,0.0,2026-03-17 23:59:59.999
14139,2026-03-18 00:00:00.000,2026-03-18 00:00:04.781,2026-03-18 00:00:04.781,0.0,0.0,0.0,2026-03-18 00:00:04.764

In [ ]:
#Sprawdzanie zakresu wartości

In [19]:
df["Score"].min()

np.float64(0.0)

In [20]:
df["Score"].max()

np.float64(100.0)

In [ ]:
#Konwersja wyników stresu do liczb naturalnych

In [56]:
df=df.apply(lambda x: x.apply(lambda x: int(x) if not isnan(x) else -1) if x.name in ["Max", "Min", "Score"] else x)

In [ ]:
#Sprawdzenie gdzie dane były Nan

In [67]:
wrong = df[df["Min"] == -1]

In [60]:
wrong

,Start time,Update time,Create time,Max,Min,Score,End time
11418,2025-08-01 23:07:19.420,2025-08-01 23:07:19.532,2025-08-01 23:07:19.532,-1,-1,0,2025-08-01 23:07:19.420
11453,2025-08-04 01:15:52.965,2025-08-04 01:15:53.103,2025-08-04 01:15:53.103,-1,-1,0,2025-08-04 01:15:52.965

In [ ]:
#Usuwanie tych rekordów gdzie było nan

In [64]:
df = df.drop(df[df["Min"] == -1].index)

In [ ]:
#Zmiana dat na obiekty datetime

In [86]:
df = df.apply(lambda x: to_datetime(x, format="%Y-%m-%d %H:%M:%S.%f") if x.name in ["Start time", "Update time", "Create time", "End time"] else x)

In [92]:
df["Start time"].dtype

dtype('<M8[ns]')

In [ ]:
df.plot(x=